import turtle
stamp = turtle.clone()
stamp.shape("square")
stamp.pensize(1000)
dictionary = {"a kind of tree you can carry in your hand ____" : 'palm tree' , "What is an astronaut's favourite meal?____" : 'Launch' , "In israel there is a doctor fot every 400 person , in Chad there is a doctor for each ____" : '23,600' , "what's orange and sounds like a parrot?____" : 'carrot' , " Snake , Elephant , Tapir , ...": 'Rabbit' }
SIZE_X = 1000
SIZE_Y = 700
def answer_A():
        turtle.clear()
        turtle.goto(0,0)
        turtle.write('You answered right')
def answer_B():
        turtle.clear()
        turtle.goto(0,0)
        turtle.write('You answered wrong')
def answer_C():
        turtle.clear()
        turtle.goto(0,0)
        turtle.write('You answered wrong')
def answer_D():
        turtle.clear()
        turtle.goto(0,0)
        turtle.write('You answered wrong')
        

turtle.onkeypress(answer_A, 'a')
turtle.onkeypress(answer_B, 'b')
turtle.onkeypress(answer_C, 'c')
turtle.onkeypress(answer_D, 'd')
turtle.listen()
def riddles():
	if girl.gif.pos() == ethiopia:
		stamp.stamp()
		turtle.penup()
		turtle.goto(-SIZE_X * 0.3, SIZE_Y * 3 / 7)
		turtle.pendown()
		turtle.write("a kind of tree you can carry in your hand____")
		turtle.penup()
		turtle.goto(-SIZE_X * 0.3, SIZE_Y / 7)
		turtle.pendown()
		turtle.write("a/palm tree")
		turtle.penup()
		turtle.goto(-SIZE_X * 0.3, -SIZE_Y * 2 / 7)
		turtle.pendown()
		turtle.write("b/lost tree")
		turtle.penup()
		turtle.goto(SIZE_X * 3 /10,SIZE_Y / 7)
		turtle.pendown()
		turtle.write("c/apple tree")
		turtle.penup()
		turtle.goto(SIZE_X * 3 / 10,-SIZE_Y * 2 / 7 )
		turtle.pendown()
		turtle.write("d/dead tree")
		
	if girl.gif.pos() == madagascar:
		stamp.stamp()
		turtle.penup()
		turtle.goto(-SIZE_X * 0.3, SIZE_Y * 3 / 7 )
		turtle.pendown()
		turtle.write("What's an astronaut's favourite meal?____")
		turtle.penup()
		turtle.goto(-SIZE_X * 0.3, SIZE_Y / 7)
		turtle.pendown()
		turtle.write("a/Launch")
		turtle.penup()
		turtle.goto(-SIZE_X * 0.3, -SIZE_Y * 2 / 7)
		turtle.pendown()
		turtle.write("b/Breakfast")
		turtle.penup()
		turtle.goto(SIZE_X * 3, SIZE_Y / 7)
		turtle.pendown()
		turtle.write("c/Dinner")
		turtle.penup()
		turtle.goto(SIZE_X * 3 / 10, -SIZE_Y * 2 /7)
		turtle.pendown()
		turtle.write("d/Brunch")
			
	if girl.gif.pos() == chad:
		stamp.stamp()
		turtle.penup()
		turtle.goto(-SIZE_X * 0.3, SIZE_Y * 3 /7)
		turtle.pendown()
		turtle.write("In israel there is a doctor for every 400 person , in Chad there is 			a doctor for each____")
		turtle.penup()
		turtle.goto(-SIZE_X * 0.3, -SIZE_Y / 7)
		turtle.pendown()
		turtle.write("a/23,600")
		turtle.penup()
		turtle.goto(-SIZE_X * 0.3, -SIZE_Y * 2 / 7)
		turtle.pendown()
		turtle.write("b/24,600")
		turtle.penup()
		turtle.goto(SIZE_X * 3 /10 , SIZE_Y / 7)
		turtle.pendown()
		turtle.write("c/13,750")
		turtle.penup()
		turtle.goto(SIZE_X * 3 / 10,-SIZE_Y * 2 / 7)
		turtle.pendown()
		turtle.write("d/47,500")
		
	if girl.gif.pos() == peru:
		stamp.stamp()
		turtle.penup()
		turtle.goto(-SIZE_X * 0.3, SIZE_Y * 3 / 7)
		turtle.pendown()
		turtle.write("what's orange and sounds like a parrot?____")
		turtle.penup()
		turtle.goto(-SIZE_Y * 0.3, SIZE_Y / 7)
		turtle.pendown()
		turtle.write("a/carrot")
		turtle.penup()
		turtle.goto(-SIZE_X * 0.3, -SIZE_Y * 2 / 7)
		turtle.pendown()
		turtle.wirte("b/orange")
		turtle.penup()
		turtle.goto(SIZE_X * 3 /10, SIZE_Y / 7)
		turtle.pendown()
		turtle.write("c/tomato")
		turtle.penup()
		turtle.goto(SIZE_X * 3 / 10,-SIZE_Y * 2 / 7)
		turtle.pendown()
		turtle.write("d/potato")
		
		
	if girl.gif.pos() == afghanistan:
		stamp.stamp()
		turtle.penup()
		turtle.goto(-SIZE_X * 0.3, SIZE_Y * 3 / 7)
		turtle.pendown()
		turtle.write("Snake , Elephant , Tapir , ...")
		turtle.penup()
		turtle.goto(-SIZE_X * 0.3, SIZE_Y / 7)
		turtle.pendown()
		turtle.write("a/Rabbit")
		turtle.penup()
		turtle.goto(-SIZE_X * 0.3, -SIZE_Y * 2 / 7)
		turtle.pendown()
		turtle.write("b/Bear")
		turtle.penup()
		turtle.goto(SIZE_X * 3 /10, SIZE_Y / 7)
		turtle.pendown()
		turtle.write("c/Ostrich")
		turtle.penup()
		turtle.goto(SIZE_X * 3 / 10,-SIZE_Y * 2 / 7)
		turtle.pendown()
		turtle.write("d/Whale")
		

		
monkey = turtle.clone()
ethiopia = girl.gif.pos()
madagascar = girl.gif.pos()
chad = girl.gif.pos()
peru = girl.gif.pos()
afghanistan = girl.gif.pos()


riddles()
